# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Jarrod Visual Studio Enterprise Subscription(f8c4a946-13d7-4ad1-a3d9-7966f9de8fdd)'
    subscriptionId: 'f8c4a946-13d7-4ad1-a3d9-7966f9de8fdd'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Demo1'
    location: 'Australia Southeast'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)\**\LogicApp.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)\**\LogicApp.parameters.json'
    overrideParameters: '-logicAppName mylogicapp'
    deploymentMode: 'Incremental'